### ISSUE TITLE
can you discuss how find agent works for the Atari games

### ISSUE THREAD

**Issue by rnunziata** [AdamStelmaszczyk/dqn#1]
can you discuss how the function find_agent works for the Atari games

**Comment by AdamStelmaszczyk** [comment]
`find_agent` purpose is to find Panama Joe (which is the avatar in Montezuma's Revenge).

Unfortunately this function is a little buggy. E.g. it doesn't detect him when he is dead or when background behind him is not black. It can be improved though.

It works just by looking for a gray color that I found specific to Panama Joe (I was taking frames and looking what unique colors Joe has).

For just DQN you don't need this function. It was needed for my HER experiments. I needed to find an agent in Montezuma to apply HER.
