### ISSUE TITLE
Who play first

### ISSUE THREAD

**Issue by xixiU** [AdamStelmaszczyk/dqn#7]
thanks for your wonderful job.But I have a qustion ,in Tennis-v0 game ,your code,the blue player always wins ,i want to change to control the blue player,so the red player can win.

**Comment by AdamStelmaszczyk** [comment]
This can't be done from this repo and does not look like an easy change. Tennis-v0 is a game taken from https://github.com/openai/atari-py, which is a Python wrapper, the actual game is coded in C++ (and runs on Stella emulator). I think the red player is the computer, so a player can't control him. If you have to do that I guess you would have to create your own Tennis-v1 environment (changing Python wrappers and C++).
